package panel;
import java.io.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import utilities.herramienta;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cristian
 */
public class addCuidados extends javax.swing.JFrame {

    /**
     * Creates new form addCuidados
     */
    ArrayList<Animales> Animales;
    ArrayList<Cuidados> Cuidados;
    public addCuidados() {
        initComponents();
        Animales=new ArrayList<Animales>();
        Cuidados=new ArrayList<Cuidados>();
        herramienta.rellenar_array (Animales, "Animales.dat");
        herramienta.rellenar_array(Cuidados, "Cuidados.dat");
        rellenaComboBox();
    }
    public void vaciar (){
        recogeTipoComida.setText("");
        RecogeCantidadComida.setText("");
        RecogeCostePromedio.setText("");
        RecogePeriodicidadComida.setText("");
        recogeHabitat.setText("");
        animalCuidado.setSelectedIndex(0);
    }
    
    public void rellenaComboBox(){
        for (int i = 0; i < Animales.size(); i++) {
            animalCuidado.addItem(Animales.get(i).getName());
        } 
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        tipoComida = new javax.swing.JLabel();
        habitat = new javax.swing.JLabel();
        cantidadComida = new javax.swing.JLabel();
        costePromedio = new javax.swing.JLabel();
        periodicidadComida = new javax.swing.JLabel();
        recogeTipoComida = new javax.swing.JTextField();
        recogeHabitat = new javax.swing.JTextField();
        RecogePeriodicidadComida = new javax.swing.JTextField();
        RecogeCantidadComida = new javax.swing.JTextField();
        RecogeCostePromedio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        animalCuidado = new javax.swing.JComboBox<>();
        animal_Cuidar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setFont(new java.awt.Font("Skygraze", 0, 24)); // NOI18N
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("AÑADIR CUIDADO");

        tipoComida.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        tipoComida.setText("TIPO COMIDA");

        habitat.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        habitat.setText("habitat");

        cantidadComida.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        cantidadComida.setText("CANTIDAD COMIDA");

        costePromedio.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        costePromedio.setText("COSTE PROMEDIO");

        periodicidadComida.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        periodicidadComida.setText("periodicidad comidas");

        jButton1.setText("AÑADIR CUIDADO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        animal_Cuidar.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        animal_Cuidar.setText("ANIMAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(costePromedio)
                    .addComponent(periodicidadComida, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(habitat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadComida, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animal_Cuidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(animalCuidado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RecogeCantidadComida, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(recogeTipoComida, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(RecogePeriodicidadComida, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(RecogeCostePromedio, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(recogeHabitat, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recogeTipoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recogeHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costePromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecogeCostePromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadComida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecogeCantidadComida, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodicidadComida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecogePeriodicidadComida, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(animal_Cuidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animalCuidado, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tipoComida = recogeTipoComida.getText();
        String habitat = recogeHabitat.getText();
        float costePromedio = Float.valueOf(RecogeCostePromedio.getText());
        float cantidadComida = Float.valueOf(RecogeCantidadComida.getText());
        int periodicidadComidad = Integer.parseInt(RecogePeriodicidadComida.getText());
        String nombreAnimal = (String) animalCuidado.getSelectedItem();
        int posAnimal = buscarAnimal(nombreAnimal);
        Animales animal = Animales.get(posAnimal);
        
        Cuidados especial = new Cuidados (tipoComida, habitat, costePromedio, cantidadComida, periodicidadComidad, animal);
        Cuidados.add(especial);
        herramienta.guardar_objetos(Cuidados, "Cuidados.dat");
        vaciar();
    }//GEN-LAST:event_jButton1ActionPerformed

    public int buscarAnimal(String nombreAnimal){
        Iterator it=Animales.iterator();
        int pos=0;
        int posAnimal=0;
        while (it.hasNext()) {
            Animales animal = (Animales) it.next();
            if(animal.getName()==nombreAnimal){
                posAnimal=pos;
            }else{
                pos++;
            } 
        }
        return posAnimal;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCuidados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RecogeCantidadComida;
    private javax.swing.JTextField RecogeCostePromedio;
    private javax.swing.JTextField RecogePeriodicidadComida;
    private javax.swing.JComboBox<String> animalCuidado;
    private javax.swing.JLabel animal_Cuidar;
    private javax.swing.JLabel cantidadComida;
    private javax.swing.JLabel costePromedio;
    private javax.swing.JLabel habitat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel periodicidadComida;
    private javax.swing.JTextField recogeHabitat;
    private javax.swing.JTextField recogeTipoComida;
    private javax.swing.JLabel tipoComida;
    // End of variables declaration//GEN-END:variables
}
