/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import panel.*;
import utilities.herramienta;

/**
 *
 * @author Cristian
 */
public class panelControl extends javax.swing.JFrame {
    DefaultTableModel modelo;
    ArrayList <Animales> listaAnimal;
    ArrayList <Cuidados> listaCuidados;
    ArrayList <Especialidad> listaEspecialidad;
    ArrayList <Cuidadores> listaCuidadores;
    /**
     * Creates new form panelControl
     */
    public panelControl() {
        initComponents();
        modelo= (DefaultTableModel) jTable1.getModel();
        listaAnimal=new ArrayList<Animales>();
        listaCuidados=new ArrayList<Cuidados>();
        listaEspecialidad=new ArrayList<Especialidad>();
        listaCuidadores=new ArrayList<Cuidadores>();
        
        herramienta.rellenar_array(listaAnimal, "Animales.dat");
        herramienta.rellenar_array(listaCuidados, "Cuidados.dat");
        herramienta.rellenar_array(listaEspecialidad, "especialidad.dat");
        herramienta.rellenar_array(listaCuidadores, "Cuidadores.dat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        especialidad = new javax.swing.JButton();
        animales = new javax.swing.JButton();
        cuidados = new javax.swing.JButton();
        cuidadores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        especialidad.setText("Especialidad");
        especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadActionPerformed(evt);
            }
        });

        animales.setText("Animales");
        animales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalesActionPerformed(evt);
            }
        });

        cuidados.setText("Cuidados");
        cuidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuidadosActionPerformed(evt);
            }
        });

        cuidadores.setText("Cuidadores");
        cuidadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuidadoresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Skygraze", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Información");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(animales, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuidados, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuidadores, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuidados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuidadores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalesActionPerformed
        // TODO add your handling code here:
        modelo.getDataVector().removeAllElements();
        
        String [] titulo={"Nombre","Especie","Subespecie","Peso"};
        modelo.setColumnIdentifiers(titulo);
        for (int i = 0; i < listaAnimal.size(); i++) {
            Animales e= listaAnimal.get(i);
            Object row[]={e.getName(),e.getEspecie(),e.getSubespecie(),e.getPeso()};
            modelo.addRow(row);
        }
    }//GEN-LAST:event_animalesActionPerformed

    private void cuidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuidadosActionPerformed
        // TODO add your handling code here:
        modelo.getDataVector().removeAllElements();
        String [] titulo={"Comida","Habitat","Coste","Cantidad","Periodicidad","Animal"};
        modelo.setColumnIdentifiers(titulo);
        for (int i = 0; i < listaCuidados.size(); i++) {
            Cuidados e= listaCuidados.get(i);
            Object row[]={e.getTipoComida(),e.getHabitat(),e.getCostePromedio(),e.getCantidadComidaKG(),e.getPeriodicidadComidaDias(),e.getAnimal().getName()};
            modelo.addRow(row);
        }
    }//GEN-LAST:event_cuidadosActionPerformed

    private void especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadActionPerformed
        // TODO add your handling code here:
        modelo.getDataVector().removeAllElements();
        String [] titulo={"Nombre","Salario medio","Extra por peligrosidad"};
        modelo.setColumnIdentifiers(titulo);
        for (int i = 0; i < listaEspecialidad.size(); i++) {
            Especialidad e= listaEspecialidad.get(i);
            Object row[]={e.getNombreEspecialidad(),e.getSalarioMedio(),e.getExtraPeligrosidad()};
            modelo.addRow(row);
        }
    }//GEN-LAST:event_especialidadActionPerformed

    private void cuidadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuidadoresActionPerformed
        // TODO add your handling code here:
        modelo.getDataVector().removeAllElements();
        String [] titulo={"Nombre","Apellidos","ID","Especialidad","Animal Cuidado"};
        modelo.setColumnIdentifiers(titulo);
        for (int i = 0; i < listaCuidadores.size(); i++) {
            Cuidadores e= listaCuidadores.get(i);
            Object row[]={e.getNombre(),e.getApellidos(),e.getIdCuidador(),e.getEspecialidad().getNombreEspecialidad(),e.getAnimalCuidado().getName()};
            modelo.addRow(row);
        }
    }//GEN-LAST:event_cuidadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton animales;
    private javax.swing.JButton cuidadores;
    private javax.swing.JButton cuidados;
    private javax.swing.JButton especialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
