/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.util.ArrayList;
import utilities.herramienta;
/**
 *
 * @author Cristian
 */
public class Registro extends javax.swing.JFrame {
    ArrayList <User> Usuarios;
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        Usuarios = new ArrayList<User>();
        herramienta.rellenar_array(Usuarios, "Usuarios.dat");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        recogerUser = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        recogerApellidos = new javax.swing.JTextField();
        apellidos = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        recogerName = new javax.swing.JTextField();
        recogerPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Skygraze", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 61, 165));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 130));

        user.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        user.setText("USER");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 140, 50));

        pass.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        pass.setText("PASSWORD");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 140, 50));
        jPanel1.add(recogerUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 380, 50));

        registrar.setBackground(new java.awt.Color(61, 61, 195));
        registrar.setFont(new java.awt.Font("Skygraze", 0, 11)); // NOI18N
        registrar.setText("SING UP");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jPanel1.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 210, 70));
        jPanel1.add(recogerApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 380, 50));

        apellidos.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        apellidos.setText("LAST NAME");
        jPanel1.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 140, 50));

        name.setFont(new java.awt.Font("Skygraze", 0, 14)); // NOI18N
        name.setText("NAME");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, 50));
        jPanel1.add(recogerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 380, 50));
        jPanel1.add(recogerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 380, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:
        String nombre = recogerName.getText();
        String apellidos = recogerApellidos.getText();
        String usuario = recogerUser.getText();
        String contrasenia= recogerPass.getText();
        
        User u = new User(nombre,apellidos,usuario,contrasenia);
        Usuarios.add(u);
        herramienta.guardar_objetos(Usuarios, "Usuarios.dat");
    }//GEN-LAST:event_registrarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField recogerApellidos;
    private javax.swing.JTextField recogerName;
    private javax.swing.JTextField recogerPass;
    private javax.swing.JTextField recogerUser;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
